"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { ClosureDay, ReplenishmentAnalysis } from "@/lib/replenishment";
import type { CustomClosure, ProductSupplierConfig, PurchaseOrder, Supplier } from "@/lib/replenishment-db";
import type { Product } from "@/lib/types";
import { Froggy } from "../components/froggy";

type Dashboard = { generatedAt: string; sourceNote: string; analyses: ReplenishmentAnalysis[]; suppliers: Supplier[]; configs: ProductSupplierConfig[]; closures: CustomClosure[]; holidays: ClosureDay[]; history: PurchaseOrder[] };
const rs = (n: number) => `Rs. ${Math.round(n).toLocaleString("en-LK")}`;
const dayName = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
const statusMeta = {
  order_now: ["Order now", "bg-danger-bg text-danger-ink border-danger-line", "🔥"], setup_needed: ["Setup needed", "bg-grape-tint text-grape-dark border-grape/30", "⚙️"],
  watch: ["Watch", "bg-flame-tint text-flame-dark border-flame/30", "👀"], already_ordered: ["Inbound", "bg-sky-tint text-sky-dark border-sky/30", "🚚"],
  no_demand_data: ["Learning", "bg-surface-soft text-ink-soft border-cardline", "◌"], healthy: ["Healthy", "bg-pond text-frog-dark border-frog/30", "✓"],
} as const;

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1.5 text-sm font-extrabold text-ink"><span>{label}</span>{children}</label>; }
const inputClass = "min-h-11 rounded-xl border-2 border-cardline bg-surface px-3 font-bold text-ink outline-none transition focus:border-frog focus:ring-4 focus:ring-frog/10";

function Runway({ item }: { item: ReplenishmentAnalysis }) {
  const demandToArrival = item.adjustedDailyRate * item.exposureDays;
  const floor = item.currentStock + item.openInboundUnits - demandToArrival;
  const thresholdAt = Math.max(24, Math.min(52, item.currentStock > 0 ? (item.reorderPoint / Math.max(item.currentStock, item.reorderPoint)) * 44 : 28));
  const arrivalAt = 78;
  return <figure className={`mt-3 rounded-2xl border-2 p-3 ${item.status === "order_now" ? "border-flame/50 bg-flame-tint/40" : "border-cardline bg-surface-soft"}`} aria-label={`Supply runway, projected floor ${Math.round(floor)} units`}>
    <div className="flex items-center justify-between gap-2"><h4 className="font-display text-sm font-extrabold text-ink">Supply runway</h4><strong className={`rounded-lg px-2 py-1 text-xs font-extrabold ${floor < 0 ? "bg-danger-bg text-danger-ink" : "bg-pond text-frog-dark"}`}>Floor {Math.round(floor)}u</strong></div>
    <div className="relative mt-1 h-24 overflow-hidden">
      <div className="absolute inset-x-2 top-10 h-3 rounded-full bg-track" />
      <div className={`absolute left-2 top-10 h-3 rounded-l-full ${item.status === "order_now" ? "bg-flame" : "bg-frog"}`} style={{ width: `calc(${arrivalAt}% - .5rem)` }} />
      {item.openInboundUnits > 0 && <div className="absolute top-10 h-3 rounded-r-full bg-sky" style={{ left: `${arrivalAt}%`, right: ".5rem" }} />}
      <Milestone position={2} top label="Today" detail={`${item.currentStock}u`} tone="ink" />
      <Milestone position={thresholdAt} label="Reorder" detail={`${item.reorderPoint}u`} tone={item.status === "order_now" ? "flame" : "ink"} />
      {item.skippedClosures.slice(0, 2).map((closure, index) => <Milestone key={`${closure.date}-${index}`} position={Math.min(arrivalAt - 8, thresholdAt + 12 + index * 12)} top label="Closed" detail={closure.date.slice(5)} tone="grape" title={closure.name} />)}
      <Milestone position={arrivalAt} label="Arrives" detail={item.expectedArrivalDate.slice(5)} tone="sky" />
    </div>
    <figcaption className="flex flex-wrap items-center justify-between gap-2 border-t-2 border-cardline pt-2 text-xs font-bold text-ink-soft"><span>Stock burns at {item.adjustedDailyRate.toFixed(1)} units/day</span><span>{item.openInboundUnits > 0 ? <><b className="text-sky-dark">{item.openInboundUnits}u inbound</b> lifts the runway</> : "No inbound stock"}</span></figcaption>
  </figure>;
}

function Milestone({ position, label, detail, tone, top=false, title }: { position:number; label:string; detail:string; tone:"ink"|"flame"|"grape"|"sky"; top?:boolean; title?:string }) {
  const colors={ink:"bg-ink text-surface",flame:"bg-flame text-white",grape:"bg-grape text-white",sky:"bg-sky text-white"};
  return <span className="absolute top-7 -translate-x-1/2" style={{left:`${position}%`}} title={title}><span className={`mx-auto block h-9 w-1 rounded ${colors[tone]}`}/><span className={`absolute left-1/2 w-16 -translate-x-1/2 text-center text-[9px] font-extrabold uppercase leading-tight ${top?"bottom-10":"top-10"}`}><b className="block text-ink">{label}</b><span className="text-ink-soft">{detail}</span></span></span>;
}

function Spark({ values }: { values: { units: number }[] }) { const max = Math.max(1, ...values.map((x)=>x.units)); return <div className="flex h-16 items-end gap-[2px]" aria-label="28 day demand bars">{values.map((x,i)=><span key={i} className={`min-w-0 flex-1 rounded-t ${i >= 21 ? "bg-sky" : "bg-frog/55"}`} style={{ height: `${Math.max(3,(x.units/max)*100)}%` }} title={`${x.units} units`} />)}</div>; }

export default function InventoryPage() {
  const [data, setData] = useState<Dashboard | null>(null); const [products, setProducts] = useState<Product[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(""); const [notice, setNotice] = useState("");
  const [section, setSection] = useState<"plan"|"suppliers"|"calendar"|"history">("plan"); const [expanded, setExpanded] = useState<string | null>(null); const [composer, setComposer] = useState<ReplenishmentAnalysis | null>(null); const [draft, setDraft] = useState<PurchaseOrder | null>(null); const [message, setMessage] = useState("");
  const [supplierForm, setSupplierForm] = useState({ id:"", name:"", whatsapp_phone:"", lead_time_working_days:1, working_weekdays:[1,2,3,4,5,6], active:true, automatic_send:false }); const [confirmAuto, setConfirmAuto] = useState(false);
  const [configForm, setConfigForm] = useState({ product_id:"", supplier_id:"", moq:1, pack_size:1, supplier_sku:"", unit_cost:"", target_cover_days:14 }); const [closureForm, setClosureForm] = useState({ date:"", name:"", supplier_id:"" });

  const load = useCallback(async () => { setError(""); try { const [a,p] = await Promise.all([fetch("/api/replenishment",{cache:"no-store"}),fetch("/api/products",{cache:"no-store"})]); const aj=await a.json(), pj=await p.json(); if(!a.ok) throw new Error(aj.error); setData(aj); if(p.ok)setProducts(pj.products); } catch(e){setError(e instanceof Error?e.message:"Could not load stock plan");}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  const totals=useMemo(()=>({action:data?.analyses.filter(x=>["order_now","setup_needed"].includes(x.status)).length??0,units:data?.analyses.reduce((s,x)=>s+x.recommendedQuantity,0)??0,value:data?.analyses.reduce((s,x)=>s+x.estimatedPurchaseValue,0)??0}),[data]);
  const nextClosure=data?.holidays.find(x=>x.date>=new Date().toISOString().slice(0,10));

  async function request(item:ReplenishmentAnalysis){setBusy(`draft:${item.productId}`);setError("");try{const r=await fetch("/api/replenishment/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({supplierId:item.supplierId,lines:[{productId:item.productId,quantity:item.recommendedQuantity}]})});const j=await r.json();if(!r.ok)throw new Error(j.error);setDraft(j.order);setMessage(j.order.message_body);setComposer(item);}catch(e){setError(e instanceof Error?e.message:"Draft failed");}finally{setBusy("");}}
  async function send(){if(!draft)return;setBusy("send");try{const r=await fetch(`/api/replenishment/orders/${draft.id}/send`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messageBody:message})});const j=await r.json();if(!r.ok)throw new Error(j.error);setNotice("Purchase request sent and recorded.");setComposer(null);setDraft(null);await load();}catch(e){setError(e instanceof Error?e.message:"Send failed");await load();}finally{setBusy("");}}
  async function saveSupplier(autoApproved=false){if(supplierForm.automatic_send&&!autoApproved){setConfirmAuto(true);return;}setBusy("supplier");try{const body={...supplierForm,id:supplierForm.id||undefined};const r=await fetch("/api/replenishment/suppliers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error);setNotice("Supplier saved.");setSupplierForm({id:"",name:"",whatsapp_phone:"",lead_time_working_days:1,working_weekdays:[1,2,3,4,5,6],active:true,automatic_send:false});setConfirmAuto(false);await load();}catch(e){setError(e instanceof Error?e.message:"Save failed");}finally{setBusy("");}}
  async function saveConfig(){setBusy("config");try{const r=await fetch("/api/replenishment/config",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...configForm,unit_cost:configForm.unit_cost===""?null:Number(configForm.unit_cost),preferred:true})});const j=await r.json();if(!r.ok)throw new Error(j.error);setNotice("Product supply rules saved.");await load();}catch(e){setError(e instanceof Error?e.message:"Save failed");}finally{setBusy("");}}
  async function saveClosure(){setBusy("closure");try{const r=await fetch("/api/replenishment/closures",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...closureForm,supplier_id:closureForm.supplier_id||null})});const j=await r.json();if(!r.ok)throw new Error(j.error);setClosureForm({date:"",name:"",supplier_id:""});setNotice("Courier closure added.");await load();}catch(e){setError(e instanceof Error?e.message:"Save failed");}finally{setBusy("");}}
  async function receive(po:PurchaseOrder){setBusy(`receive:${po.id}`);try{const receipts=po.lines.filter(x=>x.received_quantity<x.ordered_quantity).map(x=>({lineId:x.id,quantity:x.ordered_quantity-x.received_quantity,unitCost:x.unit_cost??0}));const r=await fetch(`/api/replenishment/orders/${po.id}/receive`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({idempotencyKey:`ui-${po.id}-${Date.now()}`,receipts})});const j=await r.json();if(!r.ok)throw new Error(j.error);setNotice("Stock received. On-hand quantity and weighted cost are updated.");await load();}catch(e){setError(e instanceof Error?e.message:"Receipt failed");}finally{setBusy("");}}

  if(!data&&!error)return <main className="mx-auto max-w-7xl p-4 sm:p-6" aria-busy="true"><div className="card3d flex items-center gap-4 p-5"><Froggy mood="thinking" size={70}/><div><h1 className="font-display text-2xl font-extrabold">Reading the supply runway…</h1><p className="font-bold text-ink-soft">Checking demand, stock, inbound orders and courier days.</p></div></div></main>;
  if(!data&&error)return <main className="mx-auto grid min-h-[65dvh] max-w-2xl place-items-center p-4 pb-24"><section className="card3d w-full border-l-[8px] !border-l-flame p-6 text-center"><Froggy mood="thinking" size={88}/><p className="font-display text-xs font-extrabold uppercase tracking-wider text-flame-dark">Planner unavailable</p><h1 className="mt-1 font-display text-2xl font-extrabold">We couldn&apos;t verify this stock plan</h1><p className="mt-2 font-bold text-ink-soft">Your inventory numbers are hidden until the workspace connection is restored. Sign in again if your session expired, or retry now.</p><p className="mt-3 rounded-xl bg-surface-soft p-3 text-sm font-bold text-ink-soft">{error.includes("tenant context") ? "Your workspace session is missing or expired." : error}</p><div className="mt-5 flex flex-col gap-2 sm:flex-row sm:justify-center"><a href="/login" className="btn3d border-sky-dark bg-sky text-white">Go to sign in</a><button onClick={()=>void load()} className="btn3d border-frog-dark bg-frog text-white">Retry connection</button></div></section></main>;
  return <main className="mx-auto max-w-7xl space-y-4 p-3 pb-28 sm:p-5 lg:pb-5">
    <header className="card3d relative overflow-hidden border-l-[7px] !border-l-frog p-4 sm:p-5"><div className="absolute right-4 top-1 hidden opacity-90 sm:block"><Froggy mood={totals.action?"thinking":"happy"} size={78}/></div><p className="font-display text-xs font-extrabold uppercase tracking-[.18em] text-frog-dark">Continuous supply control</p><h1 className="font-display text-3xl font-extrabold tracking-tight text-ink">Stock Planner</h1><p className="max-w-xl font-bold text-ink-soft">Know what to reorder before you run out.</p><p className="mt-2 max-w-4xl text-xs font-bold text-ink-soft">Last analysis {data?new Date(data.generatedAt).toLocaleString("en-LK"):"—"} · {data?.sourceNote}</p></header>
    {(error||notice)&&<div role="status" className={`rounded-2xl border-2 p-3 font-bold ${error?"border-danger-line bg-danger-bg text-danger-ink":"border-frog/30 bg-pond text-frog-dark"}`}>{error||notice}<button className="float-right min-h-11 px-2" onClick={()=>{setError("");setNotice("");}} aria-label="Dismiss">✕</button></div>}
    <section className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric icon="🔥" label="Need action" value={String(totals.action)} tone="flame"/><Metric icon="📦" label="Units suggested" value={String(totals.units)} tone="frog"/><Metric icon="💰" label="Purchase estimate" value={rs(totals.value)} tone="grape"/><Metric icon="◆" label="Next closure" value={nextClosure?`${nextClosure.date.slice(5)} · ${nextClosure.name}`:"None scheduled"} tone="sky"/></section>
    <nav aria-label="Stock planner sections" className="grid grid-cols-2 gap-2 sm:flex">{([["plan","Recommendations"],["suppliers","Suppliers & rules"],["calendar","Courier calendar"],["history","Request history"]] as const).map(([id,label])=><button key={id} onClick={()=>setSection(id)} className={`min-h-11 rounded-xl border-2 px-3 font-display text-xs font-extrabold sm:px-4 sm:text-sm ${section===id?"border-frog bg-pond text-frog-dark":"border-cardline bg-surface text-ink"}`}>{label}</button>)}</nav>
    {section==="plan"&&<section className="space-y-3" aria-labelledby="recommendations-title"><div className="flex flex-col items-start gap-2 min-[420px]:flex-row min-[420px]:items-end min-[420px]:justify-between"><div><h2 id="recommendations-title" className="font-display text-2xl font-extrabold">Morning reorder queue</h2><p className="text-sm font-bold text-ink-soft">Most urgent first. No message is sent until you review it.</p></div><button onClick={()=>void load()} className="btn3d shrink-0 border-frog-dark bg-frog text-white">Refresh</button></div>
      {data?.analyses.length===0?<Empty onSetup={()=>setSection("suppliers")}/>:data?.analyses.map(item=>{const meta=statusMeta[item.status];return <article key={item.productId} className={`card3d p-3 sm:p-4 ${item.status==="order_now"?"!border-flame":""}`}><div className="flex flex-wrap items-start justify-between gap-2"><div><span className={`inline-flex rounded-lg border px-2 py-1 text-xs font-extrabold ${meta[1]}`}>{meta[2]} {meta[0]}</span><h3 className="mt-1 font-display text-lg font-extrabold sm:text-xl">{item.productName}</h3><p className="text-xs font-bold text-ink-soft sm:text-sm">{item.supplierName??"No supplier assigned"} · confidence {item.confidence}</p></div><div className="text-right"><strong className="font-display text-2xl font-extrabold text-ink sm:text-3xl">{item.recommendedQuantity}</strong><span className="block text-[10px] font-extrabold uppercase text-ink-soft">units to buy</span></div></div>
        <dl className="mt-4 grid grid-cols-3 gap-2 sm:grid-cols-7">{[["On hand",`${item.currentStock}u`],["Daily rate",`${item.adjustedDailyRate.toFixed(1)}u`],["Cover",item.daysOfCover===null?"—":`${item.daysOfCover.toFixed(1)}d`],["Reorder at",`${item.reorderPoint}u`],["Inbound",`${item.openInboundUnits}u`],["Arrival",item.expectedArrivalDate.slice(5)],["Est. value",rs(item.estimatedPurchaseValue)]].map(([k,v])=><div key={k} className="rounded-xl bg-surface-soft p-2"><dt className="text-[10px] font-extrabold uppercase tracking-wide text-ink-soft">{k}</dt><dd className="mt-0.5 font-display font-extrabold text-ink">{v}</dd></div>)}</dl><Runway item={item}/>
        <div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>setExpanded(expanded===item.productId?null:item.productId)} className="min-h-11 rounded-xl border-2 border-cardline bg-surface px-4 font-display font-extrabold">Why this amount?</button>{item.status==="setup_needed"?<button onClick={()=>setSection("suppliers")} className="btn3d border-grape-dark bg-grape text-white">Set up supplier</button>:item.recommendedQuantity>0?<button disabled={busy===`draft:${item.productId}`} onClick={()=>void request(item)} className="btn3d border-frog-dark bg-frog text-white">{busy?"Preparing…":"Review request"}</button>:null}</div>
        {expanded===item.productId&&<div className="mt-4 grid gap-4 rounded-2xl border-2 border-sky/30 bg-sky-tint p-4 sm:grid-cols-[1fr_240px]"><div><h4 className="font-display text-lg font-extrabold">Why this amount?</h4><p className="mt-1 text-sm font-bold leading-relaxed text-ink">{item.explanation}</p><p className="mt-3 text-xs font-bold text-ink-soft">Formula: ({item.adjustedDailyRate.toFixed(2)} × {item.exposureDays} exposure days) + {item.safetyStock} safety = {item.reorderPoint} reorder point. Target adds {item.targetCoverDays} days, then MOQ/pack rounding.</p>{item.skippedClosures.map(x=><p key={x.date} className="mt-1 text-xs font-extrabold text-grape-dark">◆ {x.date}: {x.name}</p>)}</div><Spark values={item.demandSeries}/></div>}
      </article>})}
    </section>}
    {section==="suppliers"&&<section className="grid gap-4 lg:grid-cols-2"><div className="card3d p-4 sm:p-5"><h2 className="font-display text-2xl font-extrabold">Supplier directory</h2><p className="text-sm font-bold text-ink-soft">WhatsApp and courier rules used for every recommendation.</p><form className="mt-4 grid gap-3" onSubmit={e=>{e.preventDefault();void saveSupplier();}}><Field label="Supplier name"><input required className={inputClass} value={supplierForm.name} onChange={e=>setSupplierForm({...supplierForm,name:e.target.value})}/></Field><Field label="WhatsApp number"><input required inputMode="tel" placeholder="077 123 4567" className={inputClass} value={supplierForm.whatsapp_phone} onChange={e=>setSupplierForm({...supplierForm,whatsapp_phone:e.target.value})}/></Field><Field label="Lead time (working days)"><input type="number" min="1" max="30" className={inputClass} value={supplierForm.lead_time_working_days} onChange={e=>setSupplierForm({...supplierForm,lead_time_working_days:Number(e.target.value)})}/></Field><fieldset><legend className="text-sm font-extrabold">Courier delivery days</legend><div className="mt-2 flex flex-wrap gap-2">{dayName.map((d,i)=><label key={d} className={`flex min-h-11 items-center gap-2 rounded-xl border-2 px-3 font-bold ${supplierForm.working_weekdays.includes(i)?"border-sky bg-sky-tint":"border-cardline bg-surface-soft"}`}><input type="checkbox" checked={supplierForm.working_weekdays.includes(i)} onChange={()=>setSupplierForm({...supplierForm,working_weekdays:supplierForm.working_weekdays.includes(i)?supplierForm.working_weekdays.filter(x=>x!==i):[...supplierForm.working_weekdays,i]})}/>{d}</label>)}</div></fieldset><label className="flex min-h-12 items-center gap-3 rounded-xl border-2 border-danger-line bg-danger-bg p-3"><input type="checkbox" checked={supplierForm.automatic_send} onChange={e=>setSupplierForm({...supplierForm,automatic_send:e.target.checked})}/><span><strong className="block text-danger-ink">Allow automatic purchase messages</strong><small className="font-bold text-ink-soft">Critical: the daily job may send orders without review.</small></span></label><button disabled={busy==="supplier"} className="btn3d border-frog-dark bg-frog text-white">Save supplier</button></form>
        <div className="mt-5 space-y-2">{data?.suppliers.map(s=><button key={s.id} onClick={()=>setSupplierForm({...s,id:s.id})} className="flex min-h-14 w-full items-center justify-between rounded-xl border-2 border-cardline bg-surface-soft p-3 text-left"><span><strong className="block font-display">{s.name}</strong><small className="font-bold text-ink-soft">{s.whatsapp_phone} · {s.lead_time_working_days} working day{s.lead_time_working_days>1?"s":""}</small></span><span className={`text-xs font-extrabold ${s.automatic_send?"text-danger-ink":"text-sky-dark"}`}>{s.automatic_send?"AUTO ON":"REVIEW"}</span></button>)}</div></div>
      <div className="card3d p-4 sm:p-5"><h2 className="font-display text-2xl font-extrabold">Product supply rules</h2><p className="text-sm font-bold text-ink-soft">Assign a preferred supplier, pack size and cover target.</p>{!data?.suppliers.length?<p className="mt-4 rounded-xl bg-flame-tint p-3 font-bold text-flame-dark">Add a supplier first.</p>:<form className="mt-4 grid gap-3" onSubmit={e=>{e.preventDefault();void saveConfig();}}><Field label="Product"><select required className={inputClass} value={configForm.product_id} onChange={e=>setConfigForm({...configForm,product_id:e.target.value})}><option value="">Choose product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Preferred supplier"><select required className={inputClass} value={configForm.supplier_id} onChange={e=>setConfigForm({...configForm,supplier_id:e.target.value})}><option value="">Choose supplier</option>{data.suppliers.filter(s=>s.active).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field label="MOQ"><input type="number" min="1" className={inputClass} value={configForm.moq} onChange={e=>setConfigForm({...configForm,moq:Number(e.target.value)})}/></Field><Field label="Pack size"><input type="number" min="1" className={inputClass} value={configForm.pack_size} onChange={e=>setConfigForm({...configForm,pack_size:Number(e.target.value)})}/></Field><Field label="Target cover days"><input type="number" min="1" max="90" className={inputClass} value={configForm.target_cover_days} onChange={e=>setConfigForm({...configForm,target_cover_days:Number(e.target.value)})}/></Field><Field label="Supplier unit cost"><input type="number" min="0" placeholder="Use product cost" className={inputClass} value={configForm.unit_cost} onChange={e=>setConfigForm({...configForm,unit_cost:e.target.value})}/></Field></div><Field label="Supplier SKU (optional)"><input className={inputClass} value={configForm.supplier_sku} onChange={e=>setConfigForm({...configForm,supplier_sku:e.target.value})}/></Field><button disabled={busy==="config"} className="btn3d border-sky-dark bg-sky text-white">Save product rules</button></form>}<div className="mt-5 space-y-2">{data?.configs.map(c=><div key={c.id} className="rounded-xl border-2 border-cardline bg-surface-soft p-3"><strong className="font-display">{products.find(p=>p.id===c.product_id)?.name??"Product"}</strong><p className="text-sm font-bold text-ink-soft">{data.suppliers.find(s=>s.id===c.supplier_id)?.name} · MOQ {c.moq} · packs {c.pack_size} · {c.target_cover_days}d target</p></div>)}</div></div></section>}
    {section==="calendar"&&<section className="grid gap-4 lg:grid-cols-[.9fr_1.1fr]"><form className="card3d grid content-start gap-3 p-4 sm:p-5" onSubmit={e=>{e.preventDefault();void saveClosure();}}><h2 className="font-display text-2xl font-extrabold">Add courier closure</h2><p className="text-sm font-bold text-ink-soft">Use this for announced or supplier-specific shutdowns.</p><Field label="Date"><input required type="date" className={inputClass} value={closureForm.date} onChange={e=>setClosureForm({...closureForm,date:e.target.value})}/></Field><Field label="Reason"><input required placeholder="Courier New Year shutdown" className={inputClass} value={closureForm.name} onChange={e=>setClosureForm({...closureForm,name:e.target.value})}/></Field><Field label="Applies to"><select className={inputClass} value={closureForm.supplier_id} onChange={e=>setClosureForm({...closureForm,supplier_id:e.target.value})}><option value="">All suppliers</option>{data?.suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><button className="btn3d border-grape-dark bg-grape text-white">Add closure</button></form><div className="card3d p-4 sm:p-5"><h2 className="font-display text-2xl font-extrabold">Upcoming non-working dates</h2><p className="mb-4 text-sm font-bold text-ink-soft">Packaged Sri Lanka public/bank calendar + your exceptions. Check courier announcements for changes.</p><div className="space-y-2">{[...(data?.closures.map(x=>({...x,source:"custom"}))??[]),...(data?.holidays??[])].sort((a,b)=>a.date.localeCompare(b.date)).slice(0,18).map((x,i)=><div key={`${x.date}-${i}`} className="flex items-center gap-3 rounded-xl border-2 border-cardline bg-surface-soft p-3"><time className="w-14 shrink-0 rounded-lg bg-grape-tint p-2 text-center font-display font-extrabold text-grape-dark">{new Date(`${x.date}T00:00:00Z`).toLocaleDateString("en",{month:"short",day:"numeric",timeZone:"UTC"})}</time><span><strong className="block">{x.name}</strong><small className="font-extrabold uppercase text-ink-soft">{x.source}</small></span></div>)}</div></div></section>}
    {section==="history"&&<section className="space-y-3"><div><h2 className="font-display text-2xl font-extrabold">Purchase request audit</h2><p className="text-sm font-bold text-ink-soft">Every draft, send failure, retry and receipt stays visible.</p></div>{!data?.history.length?<div className="card3d p-8 text-center"><Froggy mood="idle" size={72}/><h3 className="font-display text-xl font-extrabold">No requests yet</h3><p className="font-bold text-ink-soft">Your first reviewed purchase request will appear here.</p></div>:data.history.map(po=><article key={po.id} className="card3d p-4"><div className="flex flex-wrap justify-between gap-3"><div><span className={`rounded-lg border px-2 py-1 text-xs font-extrabold ${po.status==="failed"?"border-danger-line bg-danger-bg text-danger-ink":po.status==="received"?"border-frog/30 bg-pond text-frog-dark":"border-sky/30 bg-sky-tint text-sky-dark"}`}>{po.status.toUpperCase()}</span><h3 className="mt-2 font-display text-lg font-extrabold">{po.reference} · {po.supplier_name}</h3><p className="text-sm font-bold text-ink-soft">Created {new Date(po.created_at).toLocaleString("en-LK")} · expected {po.expected_delivery_date}</p></div>{!["received","cancelled"].includes(po.status)&&<div className="flex gap-2">{po.status==="failed"&&<button onClick={()=>{setDraft(po);setMessage(po.message_body);setComposer(data.analyses.find(x=>po.lines.some(l=>l.product_id===x.productId))??null);}} className="btn3d border-flame-dark bg-flame text-white">Retry</button>}<button disabled={busy===`receive:${po.id}`} onClick={()=>void receive(po)} className="btn3d border-frog-dark bg-frog text-white">Receive stock</button></div>}</div><ul className="mt-3 grid gap-2 sm:grid-cols-2">{po.lines.map(line=><li key={line.id} className="rounded-xl bg-surface-soft p-3 font-bold">{line.product_name}: {line.received_quantity}/{line.ordered_quantity} units</li>)}</ul>{po.error&&<p className="mt-3 rounded-xl bg-danger-bg p-3 font-bold text-danger-ink">{po.error}</p>}</article>)}</section>}
    {composer&&draft&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-ink/50 p-0 sm:items-center sm:p-4" onMouseDown={e=>e.target===e.currentTarget&&setComposer(null)}><section role="dialog" aria-modal="true" aria-labelledby="composer-title" className="max-h-[92dvh] w-full max-w-2xl overflow-y-auto rounded-t-[2rem] border-2 border-cardline bg-surface p-4 shadow-2xl sm:rounded-[2rem] sm:p-6"><div className="flex justify-between"><div><p className="font-display text-xs font-extrabold uppercase tracking-wider text-frog-dark">Review before sending</p><h2 id="composer-title" className="font-display text-2xl font-extrabold">Purchase request</h2></div><button onClick={()=>setComposer(null)} className="h-11 w-11 rounded-xl border-2 border-cardline font-extrabold">✕</button></div><div className="my-4 rounded-2xl bg-surface-soft p-4"><div className="flex justify-between font-bold"><span>{composer.supplierName}</span><span>{composer.recommendedQuantity} units</span></div><p className="text-sm font-bold text-ink-soft">Expected delivery {composer.expectedArrivalDate}</p></div><Field label="WhatsApp message"><textarea rows={9} className={`${inputClass} resize-y py-3`} value={message} onChange={e=>setMessage(e.target.value)}/></Field><p className="mt-2 text-xs font-bold text-ink-soft">Manual review mode. Sending uses one stable message key, so a retry cannot duplicate an accepted WhatsApp.</p><button disabled={busy==="send"||message.trim().length<10} onClick={()=>void send()} className="btn3d mt-4 w-full border-frog-dark bg-frog text-white">{busy==="send"?"Sending safely…":"Send purchase request"}</button></section></div>}
    {confirmAuto&&<div className="fixed inset-0 z-[60] grid place-items-center bg-ink/55 p-4"><section role="alertdialog" aria-modal="true" aria-labelledby="auto-title" className="card3d max-w-md p-5"><span className="text-3xl">⚠️</span><h2 id="auto-title" className="mt-2 font-display text-2xl font-extrabold">Turn on automatic ordering?</h2><p className="mt-2 font-bold text-ink-soft">Each morning, Stock Planner may send this supplier a purchase request when stock reaches the reorder point. Holiday rules and open inbound stock are checked first, and every request is audited.</p><div className="mt-5 flex flex-col-reverse gap-2 sm:flex-row"><button onClick={()=>setConfirmAuto(false)} className="min-h-11 flex-1 rounded-xl border-2 border-cardline font-display font-extrabold">Keep manual review</button><button onClick={()=>void saveSupplier(true)} className="btn3d flex-1 border-danger-ink bg-danger-ink text-white">I understand, enable</button></div></section></div>}
  </main>;
}

function Metric({icon,label,value,tone}:{icon:string;label:string;value:string;tone:"flame"|"frog"|"grape"|"sky"}){const color={flame:"border-l-flame text-flame-dark",frog:"border-l-frog text-frog-dark",grape:"border-l-grape text-grape-dark",sky:"border-l-sky text-sky-dark"}[tone];return <div className={`rounded-xl border-2 border-l-4 border-cardline bg-surface p-2.5 ${color}`}><span className="mr-2" aria-hidden="true">{icon}</span><strong className="font-display text-lg font-extrabold leading-tight">{value}</strong><span className="mt-0.5 block text-[10px] font-extrabold uppercase tracking-wide text-ink-soft">{label}</span></div>}
function Empty({onSetup}:{onSetup:()=>void}){return <div className="card3d p-7 text-center"><Froggy mood="thinking" size={88}/><h3 className="font-display text-2xl font-extrabold">Build your supply runway</h3><p className="mx-auto mt-1 max-w-lg font-bold text-ink-soft">Add supplier → assign products → review recommendations → enable automatic sends only when you are comfortable.</p><button onClick={onSetup} className="btn3d mt-5 border-frog-dark bg-frog text-white">Add first supplier</button></div>}
